branch-defaults:
  aws-deployment:
    environment: cheerup-env
    group_suffix: null
  create-event-initial-branch:
    environment: seproject-cheerup-env
  create-project:
    environment: seproject-cheerup-env
  default:
    environment: seproject-cheerup-env
    group_suffix: null
  develop:
    environment: seproject-cheerup-env
  fix-errors:
    environment: seproject-cheerup-env
  setup-travis-integeration:
    environment: seproject-cheerup-env
environment-defaults:
  seproject-cheerup-env:
    branch: null
    repository: null
global:
  application_name: CheerUp
  branch: null
  default_ec2_keyname: cheerup-se-project
  default_platform: Python 3.11
  default_region: us-west-2
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: eb-cli
  repository: null
  sc: git
  workspace_type: Application
